server:
  port: 8395
spring:
  application:
    # 全部小写
    name: everything-demo
  data:
    elasticsearch:
      # elasticsearch集群名称
      cluster-name: elasticsearch
      # elasticsearch集群节点地址列表，用逗号分隔。如果没有指定，就启动一个客户端节点
      # 默认 9300 是 Java 客户端的端口。9200 是支持 Restful HTTP 的接口
      cluster-nodes: 192.168.253.101:9300
      repositories:
        # 开启 Elasticsearch 仓库(默认值:true)
        enabled: true
      properties:
        transport:
          tcp:
            # 连接超时的时间
            connect_timeout: 120s
        path:
          # 存储索引的位置
          home: /data/project/target/elastic

