spring:
  datasource:
    url: jdbc:mysql://192.168.253.101:3306/centOS?characterEncoding=utf8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  application:
    name: everything-order

server:
  port: 8082

eureka:
  instance:
    #在eureka客户端中显示ip地址加端口号
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  client:
    config:
      default:
        # 请求的连接超时时间
        connectTimeout: 2000
        # 请求的处理超时时间
        readTimeout: 2000