spring:
  datasource:
    url: jdbc:mysql://192.168.253.101:3306/centOS?characterEncoding=utf8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  application:
  data:
    elasticsearch:
      # elasticsearch集群名称
      cluster-name: elasticsearch
      # elasticsearch集群节点地址列表，用逗号分隔。如果没有指定，就启动一个客户端节点
      # 默认 9300 是 Java 客户端的端口。9200 是支持 Restful HTTP 的接口
      cluster-nodes: 192.168.253.101:9300
      repositories:
        # 开启 Elasticsearch 仓库(默认值:true)
        enabled: true
      properties:
        transport:
          tcp:
            # 连接超时的时间
            connect_timeout: 120s
        path:
          # 存储索引的位置
          home: /data/project/target/elastic
    name: everything-order

server:
  port: 8082

eureka:
  instance:
    #在eureka客户端中显示ip地址加端口号
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  client:
    config:
      default:
        # 请求的连接超时时间
        connectTimeout: 200000
        # 请求的处理超时时间
        readTimeout: 200000

# 日志级别
logging:
  level:
    com:
      example:
        everything:
          order: debug